apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tiny
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yinkaolotin/tiny.git
    targetRevision: main
    path: deploy/tiny
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: tiny

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
