apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tiny
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: tiny
  namespaceSelector:
    matchNames:
      - tiny
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
