apiVersion: v1
kind: Service
metadata:
  name: {{ include "tiny.name" . }}
spec:
  selector:
    {{- include "tiny.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

